### ISSUE TITLE
PROJECT CHECKLIST

### ISSUE THREAD

**Issue by n8willis** [YADAMSS/Matemasie-Font#22]
_This issue tracks checkpoints for the project long term and will be updated by reviewers and QA_

## MILESTONE 1

- [x] Concept for design
- [x] Contract Signing
- [x] GitHub setup complete
- [x] PROTOTYPE HamburgefontsivHAMBURGEFONTSIV!., “space char”
- [x] GoogleFonts Project Template
- [x] Font Building and producing artifacts in Actions tab?
- [x] Checking Fontbakery fails?
- [x] Checking glyph coverage for milestone?

- [x] Team members and reviewers added as collaborators in the repo

### Path direction correction

- [ ] Are all characters using correct path direction? Select all in font tab and fix path direction shift+command+R

### Not necessary in Repo but good for reviewers

- [ ] Proofing with font proofer or similar tools.
- [ ] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?
- [ ] Are proofs being sent to reviewers for feedback?

### Spacing

- [ ] Spacing is tested with spacing strings
- [ ] Capitals are spaced to work with lowercase letters

## MILESTONE 2

- [ ] 53+ glyphs
- [ ] 80+ glyphs, incl A-Z, a-z 0-9, punctuation
- [ ] Font Building and producing artifacts in Actions tab?
- [ ] Checking Fontbakery fails?

### Path direction correction

- [ ] Are all characters using correct path direction? Select all in font tab and fix path direction shift+command+R

### Not necessary in Repo but good for reviewers

- [ ] Proofing with font proofer or similar tools.
- [ ] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?
- [ ] Proofs are made with randomized text, and tested at the range of sizes defined in the project brief
- [ ] Are proofs being sent to reviewers for feedback?

## MILESTONE 3

- [ ] 80+ characters incl. A-Z, a-z, 0-9 in font
- [ ] Diacritics (in sets of western euro, Vietnamese, floating, attached)
- [ ] Special SSA characters/ Diacritics
- [ ] Diacritics are built from combining forms + anchor points
- [ ] Diacritics fit into vertical metrics
- [ ] Font Building and producing artifacts in Actions tab?
- [ ] Checking Fontbakery fails?

### Path direction correction

- [ ] Are all characters using correct path direction? Select all in font tab and fix path direction shift+command+R
- [ ] Are all overlaid diacritics using the same path direction?

### Spacing

- [ ] Numerals are tabular spaced 

### Not necessary in Repo but good for reviewers

- [ ] Proofing with Font Proofer or similar tools.
- [ ] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?

## MILESTONE 4

- [ ] Google Latin charset ~300 characters
- [ ] Font Building and producing artifacts in Actions tab?
- [ ] Checking Fontbakery fails?

### Path direction correction

- [ ] Are all characters using correct path direction? Select all in font tab and fix path direction shift+command+R

### Spacing

- [ ] Kerning with Kern On and reviewing kerning (lowercase-lowercase, Capital-lowercase, numerals)

### Not necessary in Repo but good for reviewers

- [ ] Proofing with Font Proofer or similar tools.
- [ ] Are proofs of all characters made? Do you have text set in the font? Are you printing and proofing?

## MILESTONE 5

- [ ] Additional fixing?
- [ ] Fontbakery Bug Fixes
- [ ] Font Building and producing artifacts in Actions tab?
- [ ] Checking Fontbakery fails?

- [ ] OpenType smart-font features build?

- [ ] Social media promotion, additional static and animated assets
produced, print-on-demand merchandise available

- [ ] Pull request to Google fonts made? Add font issue to google fonts filed?
